title: Aotearoa
description: Logbook and utilities from traveling New Zealand.
url: https://aotearoa.carlosjtacon.com

collections:
  pages:
    output: true
  photos:
    output: true

defaults:
  - scope:
      path: ""
    values:
      theme: "default"
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: /:path

  - scope:
      path: ""
      type: "photos"
    values:
      layout: "photo"
      permalink: photos/:path

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/logbook/:year-:month-:day-:title"
      layout: "logbook"

  - scope:
      path: "assets/photos"
    values:
      type: "photo"

  - scope:
      path: "assets/tracks/walks"
    values:
      type: "walks"

  - scope:
      path: "assets/tracks/logbook"
    values:
      type: "logbook"

  - scope:
      path: "assets/tracks/logbook/preview"
    values:
      type: "preview"

  - scope:
      path: "assets/images/sketchbook"
    values:
      type: "sketchbook"

  - scope:
      path: ""
      type: tracks
    values:
      layout: track
      permalink: /:category/:basename.html

exclude:
  - "*readme.md"
