title: Aotearoa
description: Logbook and utilities from traveling New Zealand.
url: https://aotearoa.carlosjtacon.com 

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: /:path
      
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/logbook/:year-:month-:day-:title"
      layout: "logbook"
      
  - scope:
      path: "assets/photos"
    values:
      type: "photo"
      
  - scope:
      path: "assets/tracks/walks"
    values:
      type: "walk"

exclude:
  - "*readme.md"
